Add
Show file tree
- tree.py

Sqlite usage
- sqlite.py
D:\GitHub\TIL\Python>python sqlite.py
>>CREATE TABLE phonebook(name text, age integer);
success
>>INSERT INTO phonebook('someone', 10);
Error: near "10": syntax error
>>INSERT INTO phonebook VALUES('someone', 10);
success
>>INSERT INTO phonebook VALUES('john', 12);
success
>>select * from phonebook;
[('someone', 10), ('john', 12)]
success

-thread_exer.py

- stock
Show Stock rate
But It is not working because loaded content doesn't include specific data..
like today value & rate